# Generated by Django 4.1.1 on 2022-10-23 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('budget', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('director', models.CharField(max_length=70)),
                ('image', models.FileField(upload_to='my_gallery')),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
