# Generated by Django 4.1.1 on 2022-10-25 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField(validators=[django.core.validators.MaxValueValidator(2.3), django.core.validators.MinValueValidator(1.3)])),
                ('genres', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.director'),
        ),
    ]
