# Generated by Django 4.1.1 on 2022-10-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_alter_movie_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
