# Generated by Django 4.1.1 on 2022-10-25 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0004_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('budget', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.FileField(upload_to='my_gallery')),
                ('description', models.CharField(max_length=10000)),
                ('director', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.director')),
            ],
        ),
    ]
