# Generated by Django 4.1.1 on 2022-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0006_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='interesting_fact',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='place_of_birth',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
