# Generated by Django 4.1.1 on 2022-10-25 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0007_director_interesting_fact_director_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='numbers_of_oscar',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
