# Generated by Django 4.1.1 on 2022-10-27 07:58

from django.db import migrations, models
import kino.validators


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0008_director_numbers_of_oscar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME_FIELD', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('image', models.FileField(default=None, null=True, upload_to='avatars', validators=[kino.validators.validate_file_extension])),
            ],
        ),
    ]
