# Generated by Django 4.1.1 on 2022-10-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0010_alter_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.FileField(null=True, upload_to='avatars'),
        ),
    ]
