# Generated by Django 4.1.1 on 2022-10-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0011_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
    ]
