# Generated by Django 4.1.1 on 2022-10-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0014_feedback_delete_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='id_movie',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='id_user',
            new_name='user',
        ),
    ]
