# Generated by Django 4.1.1 on 2022-10-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0015_rename_id_movie_feedback_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
