# Generated by Django 4.1.1 on 2022-10-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0016_remove_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kino.movie', verbose_name='фильм'),
        ),
    ]
