# Generated by Django 4.1.1 on 2022-10-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0018_feedback_rating_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
