# Generated by Django 4.1.1 on 2022-10-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0019_remove_feedback_rating_remove_feedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
