# Generated by Django 4.1.1 on 2022-10-28 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0020_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('second_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('height', models.FloatField(validators=[django.core.validators.MaxValueValidator(2.3), django.core.validators.MinValueValidator(1.3)])),
                ('image', models.FileField(null=True, upload_to='directors')),
                ('place_of_birth', models.CharField(default=None, max_length=200, null=True)),
                ('interesting_fact', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('numbers_of_oscar', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, to='kino.actor'),
        ),
    ]
