# Generated by Django 4.1.1 on 2022-10-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0023_alter_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link_on_youtube',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
