# Generated by Django 4.1.7 on 2023-10-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0024_movie_link_on_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='my_gallery'),
        ),
    ]
