# Generated by Django 4.1.7 on 2023-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0025_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, to='kino.actor'),
        ),
    ]
